### ISSUE TITLE
คุณกรณ์ของชาติพัฒนากล้าประกาศว่า "พรรคเสียงข้างมาก...ควรจัดตั้งรัฐบาลร่วมกันได้สำเร็จ" จะนับว่าสนับสนุนได้มั้ย?

### ISSUE THREAD

**Issue by rachasakr** [PanJ/road-to-376#2]
ช่วงบ่ายวันนี้ คุณกรณ์ประกาศใน Facebook ว่า "พรรคเสียงข้างมาก...ควรจัดตั้งรัฐบาลร่วมกันได้สำเร็จ" แต่ยังไม่ได้พูดตรงๆ ว่าจะยกมือให้

ควรจะรอก่อนมั้ยครับ? หรือให้เป็นยกมือให้เลย?

![image](https://github.com/PanJ/road-to-376/assets/27821769/82be4b36-ad5d-424d-9537-d0bb0b091f1a)

Ref: 
https://www.facebook.com/KornGoThailand/posts/798489364972960
https://thestandard.co/korn-support-move-forward-party/

**Comment by rachasakr** [comment]
Confirm ละ
https://www.thairath.co.th/news/politic/2695330

**Comment by PanJ** [comment]
Right now I'm using this [source](https://thestandard.co/korn-unclear-answer-on-joint-government/) (Not joining the coalition but still votes for the PM)
